name: 'Question'
description: 'Ask about usage, setup, or behavior clarification.'
title: '[Question] '
labels: ['question']
type: Question
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using **nestjs-typeorm-validator**?  
        Please check [Discussions](https://github.com/rotyro-tools/nestjs-typeorm-validator/discussions) first —  
        if it’s not answered there, ask below.

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
      placeholder: |
        How can I validate that an array of values is unique in the database?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you tried so far, and what’s unclear?
      placeholder: |
        I tried using @IsUnique but didn't find a way to validate arrays.
    validations:
      required: false
